name: Update Emacs packages

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-melpa:
    name: Update Melpa packages
    runs-on: ubuntu-latest
    if: github.repository_owner == 'garrgravarr'
    env:
        ACTION_STEP_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1.6
        with:
          channels: |-
            (list
              (channel
               (name 'guix)
               (url "https://codeberg.org/guix/guix-mirror")
               (introduction
                (make-channel-introduction
                 "9edb3f66fd807b096b48283debdcddccfea34bad"
                 (openpgp-fingerprint
                  "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure git
        run: |
          git config user.name "garrgravar-bot"
          git config user.email garrgravarr-bot@phrogstar.de
          git config receive.advertisePushOptions true

      - name: Update packages
        run: |
          guix repl -L . ./scripts/update

      - name: Commit and push
        run: |
          git pull --rebase --autostash
          git add emacs/packages
          git commit -S -m "chore: update melpa packages"
          git push
